<?php
    return array( 
      'AUTOLOAD_NAMESPACE'    => [
        'Sdk' => APP_PATH . 'Transport/Vendor/Sdk/',
      ],
        //'配置项'=>'配置值'
        'SHIP_CATE'=>[
            'cm_'=>'普通平邮',
            'ghxb_'=>'挂号',
            'kd_'=>'快递',
            'eub_'=>'EUB',
            'zx_'=>'专线'
        ],

        // 最重要的 模板配置
        'CARRIER_TEMPT'=>array(
            'wish邮特殊测试渠道-8' => 'img2',
            'wish邮特殊测试渠道-捷买送' => 'img1',
            'wish邮特殊测试渠道-顺友' => 'img1',
            'wish邮常规测试渠道-UBI' => 'img1',
            'wish邮常规测试渠道-CNE' => 'img1',
            'wish邮常规测试渠道-Wise' => 'wish_chgui_img',
            'JOOM-中欧挂号特货' => 'img1_15',
            'JOOM-中欧平邮特货' => 'img1_15',
            '德国专线-FT' => 'img1',
            '速卖通线上南京挂号-LX-8' => 'smt_nanjing_lx_img-8',
            '速卖通线上南京挂号-LX' => 'smt_nanjing_lx_img',
            '速卖通线上南京平邮-LX' => 'smt_nanjing_lx_img',
            'wish线上南京挂号-LX-8' => 'img2',
            'wish线上南京平邮-LX' => 'img1',
            'wish线上南京挂号-LX' => 'img1',
            '南京小包平邮-LX' => 'img1',
            '南京小包挂号-LX' => 'img1',
            'SpeedPAK-标准（带电）' => 'img1',
            '速卖通线上挂号-南京仓-GD-8' => 'smt_nanjing_img-8',
            '速卖通线上挂号-南京仓' => 'smt_nanjing_img',
            '速卖通线上平邮-南京仓' => 'smt_nanjing_img',
            '南京小包挂号-GD' => 'img1',
            '南京小包平邮-GD' => 'nanjingpy_lx',
            'wish线上南京挂号-GD_DE' => 'img2',
            'wish线上南京挂号-GD' => 'img1',
            'wish线上南京平邮-GD' => 'img1',
            'wish线上EUB特货-LX' => 'img2',
            '西班牙专线平邮-YD' => 'img1',
            '义速宝俄罗斯经济-YD' => 'img1',
            '英国专线挂号-YHT' => 'img1_15',
            'wish邮欧洲专线-WB' => 'img1',
            '燕文专线追踪小包-特货' => 'img1',
            '燕文专线追踪小包-普货' => 'img1',
            '台湾小包平邮-GY(ebay)' => 'img1',
            '台湾小包挂号-GY(ebay)' => 'img1',
            '圆通-shopee特货（宅配）' => 'ytshopee_img',
            '圆通-shopee特货（店配）' => 'ytshopee_img',
            '圆通-shopee普货（店配）' => 'ytshopee_img',
            '东莞小包挂号-ebay' => 'dggh',
            '东莞小包平邮-ebay' => 'dgpy',
            '英国虚拟仓平邮-FN' => 'img1',
            '巴基斯坦内置包税小包-QHY' => 'img1',
            '巴基斯坦特货包税小包-QHY' => 'img1',
            '巴基斯坦普货包税小包-QHY' => 'img1',
            '北京EUB-YW' => 'img2',
            '英国专线挂号-FT' => 'img1',
            '印度专线带电-SZYJ' => 'img1_15',
            '印度专线普货-SZYJ' => 'img1_15',
            'DHL快递小货-DH' => 'dhldunhao_img',
            'DHL快递小货-DH（带电）' => 'dhldunhao_img',
            '英国虚拟仓专线挂号-SM' => 'img1_15',
            '虚拟仓ubi加拿大特快专线' => 'imgubi',
            '英国虚拟仓平邮-AJ' => 'img1',
            'Wish邮深圳挂号-8' => 'wishyou_sz_img_8',
            'Wish邮深圳挂号' => 'img1',
            'MyMall线上小包' => 'img1_15',
            '速卖通线上菜鸟专线经济' => 'img1',
            '华中小包挂号-八国' => 'img1',
            '华中小包平邮' => 'img1',
            '华中小包挂号' => 'img1',
            '越南EUB-HYT' => 'img1',
            '速卖通线上郑州平邮-AD' => 'smt_zz_img',
            '速卖通线上郑州挂号-AD' => 'smt_zz_img',
            '速卖通线上郑州挂号-AD-8' => 'smt_zz_img-8',
            'wish线上郑州平邮-AD' => 'wishyou_zz_img',
            'wish线上郑州挂号-AD' => 'wishyou_zz_img',
            'wish线上郑州挂号-AD-8' => 'wishyou_zz_img-8',
            '美国虚拟仓普货-LZ' => 'langzhi',
            '国内快递' => 'default_lable',
            'JOOM线上东莞挂号' => 'dongguan_ems_img',
            'JOOM线上东莞平邮' => 'dongguan_ems_img',
            '比邮欧洲平邮-HYD' => 'hyd-byozpy',
            '比利时平邮-HYD' => 'img2',
            '中欧专线平邮-ebay' =>  'img1',
            'wish线上广州eub带电-AJ' => 'img2',
            'wish线上武汉eub-AJ' => 'img2',
            '美国虚拟仓普货大包-TJ' => 'tengjia',
            '美国虚拟仓内电大包-TJ' => 'tengjia',
            '美国虚拟仓特货大包-TJ' => 'tengjia',
            '美国虚拟仓特货-TJ' => 'tengjia',
            '美国虚拟仓内电-TJ' => 'tengjia',
            '美国虚拟仓普货-TJ' => 'tengjia',
            'wish邮广州挂号-WYT_DE' => 'img2',
            'wish邮广州挂号-WYT' => 'img1',
            'wish邮广州平邮-WYT' => 'img1',
            '速卖通线上挂号-HYT_CZ' => 'smt_huayuntimg_CZ',
            'wish邮成都挂号-HYT_DE' => 'wish_huayuntimg_DE',
            '速卖通线上挂号-HYT' => 'smt_huayuntimg',
            '速卖通线上平邮-HYT' => 'smt_huayuntimg',
            'wish邮成都挂号-HYT' => 'wish_huayuntimg',
            'wish邮成都平邮-HYT' => 'wish_huayuntimg',
            '印度专线-QHY' => 'img1',
            'wish香港平邮-JHD' => 'img1',
            'wish邮线上美国专线-SF' => 'img1',
            'Wish线上ubi加拿大特惠专线' => 'img2',
            '俄速通小包挂号' => 'img2',
            '顺丰东欧小包挂号' => 'img1',
            '美国专线-SF' => 'img1',
            '欧洲专线平邮-FT' => 'img1',
            'wish邮线上香港小包挂号-DSF' => 'img2',
            'wish邮线上香港小包平邮-DSF' => 'img2',
            'wish线上英国联邮通挂号特惠-DSF' => 'img1',
            'wish线上新邮挂号-DSF' => 'img2',
            'wish线上新邮微包平邮-DSF' => 'img2',
            'wish线上UBI比利时平邮'        => 'img1',
            'wish线上UBI墨西哥SCM专线挂号' => 'img1',
            'wish线上UBI澳邮专线挂号'      => 'img2',
            'wish线上UBI加拿大专线挂号'    => 'img2',
            'wish线上UBI西班牙专线平邮'    => 'img1_15',
            'JOOM-RU经济' => 'joom_img',
            'wish航空挂号小包特货-YW' => 'img1',
            'wish专线追踪小包特货-YW' => 'img1',
            'wish专线平邮小包特货-YW' => 'img1',
            'wish法国专线挂号特惠-YT' => 'img1',
            '速卖通线上俄罗斯菜鸟特货专线-简易' => 'img1',
            '速卖通线上菜鸟特货专线-超级经济'   => 'img1',
            '虚拟仓易可达USPS小包' => 'ykdhd_ups',
            '虚拟仓易可达USPS大包' => 'ykdhd_ups',
            'wish线上新加坡挂号' => 'img2',
            'wish线上新加坡平邮' => 'img2',
            '澳大利亚专线-YD' => 'img1',
            'Wish邮广州挂号'       => 'img1',
            'Wish邮广州平邮'       => 'img1',
            '速卖通线上挂号-广州仓' => 'smt_ftimg',
            '速卖通线上平邮-广州仓' => 'smt_ftimg',
            '速卖通线上挂号-广州仓_DE' => 'smt_ftimg_de',
            '荷邮纯电挂号-YD_IT' => 'img1',
            '荷邮纯电挂号-YD_CZ' => 'img1',
            '荷邮纯电挂号-YD_PL' => 'img1',
            '荷邮纯电挂号-YD_LU' => 'img1',
            '荷邮纯电挂号-YD' => 'img2',
            '荷邮纯电平邮-YD' => 'img1',
            '柬埔寨平邮-YD' => 'img1',
            '德国专线-YD' => 'img1',
            'Wsh线上EUB带电-HYD' => 'wish_eub_hyd_img2',
            'Wsh线上EUB-HYD' => 'wish_eub_hyd_img2',
            '顺邮宝挂号-SY'      => 'img1',
            'Wish线上香港挂号-YT' => 'img2',
            'Wish线上快速小包平邮-YT' => 'img1',
            'Wish线上香港平邮-YT' => 'img1',
            'Wish线上中美专线（特惠）-YT' => 'img1',
            'Wish线上中欧专线挂号-YT' => 'img1',
            'Wish线上中欧专线平邮-YT' => 'img1',
            'Wish线上西班牙特惠专线平邮-YT' => 'img1',
            'wish线上航空普货-YW'   => 'img1',
            'wish线上航空特货-YW'   => 'img1',
            'wish线上燕邮宝-YW'     => 'img1',
            'Wish线上顺邮宝平邮-SY' => 'img1',
            'Wish线上顺邮宝挂号-SY' => 'wish_shunyoubao_img',
            '顺邮宝平邮2-SY' => 'img1',
            '德国专线-DHL' => 'img1',
            '香港平邮-ZTO' => 'zt_pingyou',
            '香港挂号-ZTO' => 'zt_guahao',
            'EUB'          => 'hyd_eub',
            '线下EUB'      => 'eub',
            'EUB带电'      => 'hyd_eub',
            '线下EUB(广州)' => 'eub',
            '线下EUB带电(广州)-鼎立' => 'eub',
            '线下EUB(加拿大)鼎立' => 'img2',
            '速卖通线上小包云途' => 'smtxs',
            '速卖通线上小包平邮厦门仓' => 'smtxs',
            '速卖通线上小包挂号厦门仓' => 'smtxs',
            '速卖通线上小包(鼎立通莆田仓)' => 'smtxs',
            '速卖通线上小包挂号(鼎立莆田仓)' => 'smtxs',
            '速卖通线上小包云途挂号' => 'smtxs',
            '速卖通线上小包挂号-无锡仓'=> 'smtxs',
            '速卖通线上小包平邮-无锡仓'=> 'smtxs',
            '速卖通线上小包平邮-无锡仓_8G'=> 'img2',
            '速卖通线上小包挂号-无锡仓_8G'=> 'img2',
            '速卖通线上小包云途挂号_8G' => 'img2',
            '速卖通线上燕文航空经济小包'=>'img1',
            '速卖通线上平邮-东莞仓'=>'smtdg',
            '速卖通线上挂号-东莞仓'=>'smtdg',
            '速卖通线上顺丰航空经济小包'=>'img2',
            '速卖通线上平邮带电-深圳仓' => 'img1',
            '新加坡小包平邮-YW' => 'img1',
            '速卖通线上无忧集运平邮-SA' => 'img1',
            '速卖通线上无忧集运挂号-SA' => 'img1',
            '速卖通线上无忧集运平邮-AE' => 'img1',
            '速卖通线上无忧集运挂号-AE' => 'img1',

            /*'东莞小包挂号-八国'=>'img2',
            '东莞小包挂号-AU'=>'img2',
            '东莞小包挂号'=>'img2',
            '东莞小包平邮'=>'img2',
            '东莞小包挂号-八国_AU' => 'dggh_au',
            '东莞小包挂号-八国_5G' => 'dggh_wuguo',//欧洲5国*/

            '东莞小包挂号' => 'dggh',
            '东莞小包挂号-八国' => 'dggh',
            '东莞小包挂号-八国_DE' => 'dggh_de',
            '东莞小包挂号-八国_FR' => 'dggh_fr',
            '东莞小包挂号-八国_NZ' => 'dggh_nz',
            '东莞小包挂号-八国_AU' => 'dggh_au',
            '东莞小包挂号-八国_5G' => 'dggh_wuguo',//欧洲5国
            '东莞小包平邮' => 'dgpy',
            '东莞小包挂号-欧洲八国' => 'dggh',
            'Wish邮东莞平邮' => 'dgpy_wish',
            'Wish邮东莞挂号' => 'img1',
            '荷兰小包平邮-YW' => 'img1',
            '荷兰小包挂号-YW' => 'img1',
            '新加坡小包挂号-YW' => 'img1',
            '土耳其邮政挂号-YW' => 'img1',
            '土耳其邮政平邮-YW' => 'img1',
            '马来西亚小包挂号-YW' => 'img1',
            '马来西亚小包平邮-YW' => 'img1',
            '香港小包挂号-YW' => 'img2',
            '香港小包挂号四国-YW' => 'img2',
            '香港小包平邮-YW' => 'img2',
            '西邮经济小包-YW' => 'img2',
            '重庆小包挂号-YW' => 'img2',
            '重庆小包平邮-YW' => 'img1',
            '燕邮宝平邮内电-YW' => 'img1',
            '比利时小包平邮-YW' => 'img1',
            '比利时小包挂号-YW' => 'img2',
            '荷兰邮政小包挂号' => 'img1',
            '外电荷兰挂号-易通' => 'hxgh_yt',
            '外电荷兰平邮-易通' => 'hxpy_yt',
            '厦门小包平邮(普货)'   => 'xmpy',
            '厦门小包平邮(带电)'   => 'xmpy',
            '厦门小包挂号(普货)'   => 'xmgh',
            '厦门小包挂号(普货)-八国_DE'   => 'xmgh_de',
            '厦门小包挂号(普货)-八国_FR'   => 'xmgh_fr',
            '厦门小包挂号(普货)-八国_NZ'   => 'xmgh_nz',
            '厦门小包挂号(普货)-八国_5G'   => 'xmgh_wuguo',
            '厦门小包挂号(普货)-八国_NO'   => 'xmgh_no',
            '厦门小包挂号(普货)-八国_AU'   => 'xmgh_no',
            '厦门小包挂号(带电)'   => 'xmgh',
            '厦门小包挂号(带电)-八国_DE'   => 'xmgh_de',
            '厦门小包挂号(带电)-八国_FR'   => 'xmgh_fr',
            '厦门小包挂号(带电)-八国_NZ'   => 'xmgh_nz',
            '厦门小包挂号(带电)-八国_NO'   => 'xmgh_no',
            '厦门小包挂号(带电)-八国_5G'   => 'xmgh_wuguo',
            '厦门小包挂号(带电)-八国_AU'   => 'xmgh_no',
            '土耳其邮政平邮-易通'  => 'teqpy',
            '土耳其邮政挂号-易通'  => 'teqgh',
            '福州小包平邮'        => 'fzxbpy',
            '福州小包挂号'        => 'fzxbgh',
            '福州小包挂号_FR'     => 'fzxbgh_FR',
            '福州小包挂号_NZ'     => 'fzxbgh_NZ',
            '福州小包挂号_DE'     => 'fzxbgh_DE',
            '福州小包挂号_group1' => 'fzxbgh_Group1',
            // hank 2018/1/16 10:53 添加澳大利亚面单
            '福州小包挂号_AU'     => 'fzxbgh_AU',
            // hank 2017/12/30 11:14 改了名称要保留配置  防止要打印面单
            '中欧专线小包挂号' => 'zozxgh',
            '中欧专线挂号' => 'zozxgh',   //渠道名称更改了，abel
            '中欧专线平邮' =>  'img1',
            '俄罗斯平邮-YT' => 'img1',
            '快速小包平邮-YT' => 'img1',
            '西班牙特惠专线平邮-YT' => 'img1',
            '欧洲专线平邮-WO' =>  'img1',

            '德国专线小包挂号' => 'dgzxgh',
            '速卖通线上小包无忧标准'=> 'img1', // 一张img的
            '速卖通线上小包无忧标准（非普货）'=> 'img1', // 一张img的
            '速卖通线上小包无忧简易'=> 'img1',
            '速卖通线上小包无忧简易-西班牙'=> 'img1',
            '速卖通线上小包4PX新邮经济小包'=> 'img1',
            '速卖通线上小包中外运-西邮经济'=> 'img1',
            '速卖通线上小包顺友航空经济小包深圳仓'=> 'img1',
            '速卖通线上菜鸟经济-RU' =>  'img1',
            '速卖通线上小包无忧标准-普货' => 'img1',
            '速卖通线上小包无忧简易-ES' => 'img1',

            '欧速通'=> 'img2',
            '欧速通（带电）'=> 'img2',
            '欧速通英国专线挂号'=> 'ost_img2_15',
            '欧速通英国专线挂号(带电)'=> 'ost_img2_15',
            '俄速通'=> 'est',
            '亚欧快运陆运挂号'=> 'yolygh',
            '顺友通平邮'      => 'img1',
            '顺友通挂号'      => 'img1',
            '顺邮宝平邮'      => 'img1',
            '顺邮宝挂号'      => 'img1',
            //'顺友通平邮_UA'   => 'sytpyua',
            //'顺邮宝平邮_1'      => 'sybpy_1',
            //'顺邮宝挂号_1'      => 'sybgh_1',
            //'顺邮宝挂号_2'      => 'sybgh_2',
            '华南小包平邮（快速）' => 'hnxbpyks',
            //'华南小包平邮（快速）' => 'img1',
            'lazada物流'         => 'lazada',
            '新加坡小包平邮'      => 'img2',
            '圆通-shopee'        => 'ytshopee_img',
            'LWE'                => 'img1',
            'Linio物流'         => 'img1',
            '瑞典小包平邮-易通'      => 'rdpy',
            '瑞典小包挂号-易通'      => 'rdgh',
            '新加坡小包挂号'         => 'img2',
            // hank 2017-11-12
            '新加坡小包挂号-意大利'   => 'xjpxbgh',
            '新加坡小包挂号-五国'     => 'xjpxbgh',
            '法国专线-安骏'            => 'img1', // 'frzx_aj'
            '英国直飞专线-安骏'         => 'img2_revise', // 'gbzx_aj'
            '美国专线-安骏'             => 'img3',//'mgzxaj',
            '顺丰国际小包'              =>  'img1',

            '出口易小包平邮'            => 'img2',
            '出口易小包挂号'            => 'img2',
            '西班牙专线平邮'            => 'xbyzxpy',  // 5908458,5905568,5898773,5896714,5887498,5883505,5870067  待扫描
            '英国专线标准'              => 'ygzxbz',   // 5939539,5928009, 5922096
            '法国专线挂号'              => 'fgzxgh',   // 5940355 5938696
            '意大利专线挂号'            => 'ydlzxgh',  // 5908149,5899131
            '意大利专线平邮'            =>  'ydlzxpy', // 5744359, 5667896
            //        'DHl小包挂号'              =>  'DHLxbgh',  // 换用PDF 转图片了
            '德国专线挂号'              =>  'dgzxgh0',  // 5927849,5924049, 5923902
            '西班牙专线挂号'            =>   'xbyzxgh', // 5863156, 5847785
            '顺丰东欧小包平邮'       =>  'sfkts',
            // hank 2017/12/29 16:44
            '顺丰东欧小包平邮-JOOM'  =>  'sfkts',
            // hank 2017/11/21 9:15 添加速卖通专用kts渠道
            '顺丰东欧小包挂号-速卖通专用' =>  'sfktsgh',

            'UBI加拿大专线'      => 'imgubi',
            'UBI澳大利亚平邮（带电）' => 'imgubi',
            'UBI澳大利亚平邮'     => 'imgubi',
            'UBI澳大利亚专线（带电）' => 'imgubi',
            'UBI澳大利亚专线'     => 'imgubi',
            'UBI墨西哥专线（带电）'  => 'imgubi',
            'UBI墨西哥专线'      => 'imgubi',
            'UBI加拿大专线（带电）'  => 'imgubi',
            'UBI俄罗斯专线（带电）'  => 'imgubi',
            'UBI俄罗斯专线'      => 'imgubi',
            'UBI欧盟28国-半程查件'=> 'img1',

            '荷兰邮政小包平邮'      => 'img1',

            '线上中邮易递宝（万邑通）' => 'img1',
            '香港平邮易递宝（万邑通）' => 'img2',
            '马来西亚平邮易递宝（万邑通）' => 'img1',
            '线上中邮万邑通-深圳邮局' => 'img1',
            //'SLS-shopee专用'        => 'img3', //需要调图片的边距问题所以需要单独起一个模板文件
            '顺达宝平邮'        => 'img1', //需要调图片的边距问题所以需要单独起一个模板文件
            '广州小包挂号'      => 'img2',
            '广州小包平邮'      => 'img2',
            '线下EUB(广州)-鼎立' => 'eub',
            'DHL小包挂号-德国预清关' => 'img2',
            'DHL小包平邮-德国预清关' => 'img2',
            'DHl小包挂号'           =>  'img2',
            'DHl小包挂号(带电)'     => 'img2',
            // hank 2018/3/30 13:46
            'DHL小包平邮'     => 'img2',
            'DHL小包平邮(带电)'     => 'img2',
            '华南小包挂号'        => 'hnxbgh',
            '中美专线（特惠）'     => 'zmzx',
            '德国专线平邮'     => 'img1',
            'Wish平邮-广州仓'     => 'img1',
            '广州小包平邮-星邮'     => 'img1',
            '广州小包挂号-星邮'     => 'img1',
            '港俄航空专线－东擎'     => 'dongqing1',
            '易可达虚拟仓换单前'     => 'ykdhd',
            '比利时小包'     => 'blsxb',
            '比利时小包非欧盟'     => 'img2', //blsfom
            //'E速宝'     => 'img2',
            'E速宝'     => 'esb',
            'E速宝(RU)' => 'esb',
            //Abel  2017-11-6
            '中美专线' => 'zmph',
            '中美专线-带电' => 'zmdd',
            'IB中美专线（标准）' => 'img1',
            'IB中美专线（快速-带电）' => 'img1',
            //将面单转化为两张
            '顺丰荷兰小包挂号'  => 'img2_cbte',
            '顺丰荷兰小包平邮'  => 'img2_cbte',
            '顺丰澳大利亚小包挂号'  => 'img2_cbte',

            'CTAM小包平邮'     => 'img1',
            '俄罗斯小包WH'     => 'img2',
            '新疆小包挂号-WH'     => 'img1',
            'SLS-shopee专用' =>'shopee_img',
            'SLS-shopee专用(越南)' =>'shopee_img',
            'SLS-shopee （印度尼西亚）' => 'shopee_img',
            'SLS-shopee（马来西亚）' => 'shopee_img',
            'SLS-shopee（泰国）' => 'shopee_img',
            'SLS-shopee（新加坡）' => 'shopee_img',
            'SLS-shopee  Standar EKspres印尼' => 'shopee_img',
            'DHL-shopee（泰国）' => 'shopee_img',
            '法国专线-万欧' =>'img1',
            '德国专线-万欧' =>'img1',
            '意大利专线-万欧' =>'img1',
            '西班牙专线-万欧' =>'img1',
            '法国专线标准-WB' => 'img1',

            '线下EUB广州-YLD' =>'eubyld',
            '线下EUB广州(带电)-YLD' =>'eubyld',
            '线下EUB-南京' =>'eub',
            'EUB-南京' =>'eub',
            '老挝小包平邮-TY' =>'img1',
            '老挝小包挂号-TY' =>'img1',
            '老挝小包平邮快线-TY' =>'tongyou_img',
            //'SRM简易挂号-俄罗斯' =>'img1_15',
            //'RM挂号-俄罗斯' =>'img1_15',
            'jumia Soko物流'=>'img1_jm',
            'jumia Soko物流-埃及'=>'img1_jm',
            '速卖通线上小包挂号-南京仓' =>'smtdg',
            '速卖通线上小包平邮-南京仓'=>'smtdg',
            // hank 2017/11/9 15:43
            '北京小包平邮-YW' =>'img1',
            '北京小包挂号-YW' =>'img2',
            'Wish邮平邮-YW' =>'img1',
            // hank 2017/11/16 14:58 速卖通线上顺丰国际经济小包
            '速卖通线上顺丰国际经济小包'=>'img1',
            // hank 2017/11/22 13:50
            '速卖通线上无忧优先'=>'img1',
            '中国邮政EMS'=>'emsgj',
            '联邮通英国专线挂号'=>'lytgh',
            '联邮通英国专线挂号特惠'=>'img1',
            // hank 2017/11/23 14:08
            'SLS平邮-shopee专用'=>'shopee_img',
            'SLS平邮-shopee专用（越南）' => 'shopee_img',
            // hank 2017/11/24 16:41
            '美国专线-DHL'=>'img1',
            // hank 2017/11/28 11:03
            '俄罗斯平邮-EST'=>'estpy',
            // hank 2017/12/4 14:33
            'DHL出口'=>'dhlck',
            '华南小包挂号-五国'=>'hnxbgh',
            // hank 2017/12/13 14:11
            'Wish邮平邮-DL'=>'img1',
            // hank 2018/1/25 19:13
            '东莞小包挂号-AU'=>'dggh_au',
            // hank 2018/1/30 16:10
            '燕邮宝平邮-YW'=>'img1',
            '航空经济小包普货-YW'=>'img1',
            '航空经济小包特货-YW'=>'img1',
            '航空挂号小包普货-YW'=>'img1',
            '航空挂号小包特货-YW'=>'img1',
            '英国专线微包-YW'=>'img1',
            'DHL经济平邮'=>'img2',
            'CTAM小包平邮-普货'=>'img1',
            'CTAM小包挂号'=>'img1',
            '英国专线平邮-FT' => 'img1',
            '意大利专线平邮-FT' => 'img1',
            //abel 2018 02 01
            '台湾小包挂号-GY'=>'img1',
            '台湾小包平邮-GY' => 'img1',
            // hank 2018/2/1 18:08
            'E速宝挂号'=>'esbgh',
            'E速宝挂号-RU'=>'esbgh_RU',
            'E速宝挂号-BR'=>'esbgh_BR',
            // hank 2018/2/28 14:52
            'Wish邮挂号-YW'=>'img1',
            'CTAM小包平邮-液体'=>'img1',
            '中欧特快专线平邮'=>'img1',
            // hank 2018/3/15 9:42
            'Wish邮南京挂号-YW'=>'img1',
            'Wish邮南京平邮-YW'=>'img1',
            '比邮挂号-WH'=>'img2',
            '比邮平邮-WH'=>'img1',
            '比邮挂号26国-WH'=>'img2',
            '英国虚拟仓平邮'=>'img1',
            // hank 2018/3/26 11:48
            '厦门挂号带电-GD'=>'xmxb',
            '厦门挂号-GD'=>'xmxb',
            '厦门平邮带电-GD'=>'xmxb',
            '厦门平邮-GD'=>'xmxb',
            // hank 2018/3/30 16:50
            'Wish邮厦门挂号-GD'=>'img1',
            'Wish邮厦门平邮-GD'=>'img1',
            'Wish邮厦门挂号带电-GD'=>'img1',
            'Wish邮厦门平邮带电-GD'=>'img1',
            //'Wish邮东莞平邮' => 'img1',
            'Wish邮深圳平邮' => 'img1',
            'Wish邮深圳平邮（带电）' => 'img1',
            'wish线上Fly挂号-FT' => 'img1',
            'wish线上Fly平邮-FT' => 'img1',
            'Wish线上老挝平邮' => 'img1',
            'Wish线上老挝平邮-特货' => 'img1',
            // hank 2018/4/2 14:15
            '新疆EUB-WH'=>'img2',
            '新疆中邮挂号-WH' => 'img1',
            // mina 20180409
            '香港挂号-JHD' => 'jhd_img',
            '香港平邮-JHD' => 'jhd_img',
            '香港wish平邮-JHD' => 'jhd_img',
            'GLS物流' => 'gls_img', // mina 20180420
            '卢森堡挂号' => 'img1',
            '线下EUB郑州-WH' =>'zhz_wh',

            'SpeedPAK-经济' => 'ebay_img',
            'SpeedPAK-标准' => 'ebay_img',
            'jumia Soko物流-象牙海岸' => 'img1_jm',
            'ECMS-wadi' => 'img1',
            'EPC-Wish' => 'img1',
            'EPC-Wish特货' => 'img1',

            'JOOM-RU简易' => 'joom_img',
            'JOOM-RU挂号' => 'joom_img',
            'JOOM-RU挂号特货' => 'img1_15', //'joom_img_tehuo',
            'JOOM-中欧挂号' => 'img1',
            'JOOM-中欧平邮' => 'img1',

            '深圳小包SH挂号' => 'szshgh',
            '深圳小包SH平邮' => 'szshpy',
            '深圳小包SH平邮_US' => 'szshpy_us',
            '深圳小包SH平邮_RU' => 'szshpy_ru',
            '深圳小包SH平邮_GB' => 'szshpy_gb',
            '深圳小包SH跟踪'    => 'szshgz',
            '深圳小包SH跟踪-AU' => 'szshgzau',
            '深圳小包SH跟踪-PM' => 'szshgzpm'
        ),


        /**
        *测试人员谭 2018-08-14 17:35:12
        *说明:TODO 10*15 的 请IT人员注意！ 除非万不得已，不要新增10*15面单 如果新增了请通知仓库！
        */
        // 10*15 的面单尺寸配置
        'CARRIER_TEMPT_15'=>array(
            'JOOM-中欧挂号特货' => 1,
            'JOOM-中欧平邮特货' => 1,
            'JOOM-RU挂号特货' => 1,
            '英国专线挂号-YHT' => 1,
            '英国虚拟仓专线挂号-SM' => 1,
            'wish线上UBI西班牙专线平邮' => 1,
            '欧速通英国专线挂号'      => 1,
            '欧速通英国专线挂号(带电)'      => 1,
            '美国虚拟仓特货-TJ' => 1,
            '美国虚拟仓内电-TJ' => 1,
            '美国虚拟仓普货-TJ' => 1,
            '美国虚拟仓普货大包-TJ' => 1,
            '美国虚拟仓内电大包-TJ' => 1,
            '美国虚拟仓特货大包-TJ' => 1,
            '印度专线带电-SZYJ' => 1,
            '印度专线普货-SZYJ' => 1,
            'MyMall线上小包' => 1
//            '出口易小包平邮'       => 1,
//            '出口易小包挂号'       => 1,
            //'UBI加拿大专线'      => 1,
            //'UBI澳大利亚平邮（带电）' => 1,
            //'UBI澳大利亚平邮'     => 1,
            //'UBI澳大利亚专线（带电）' => 1,
            //'UBI澳大利亚专线'     => 1,
            //'UBI墨西哥专线（带电）'  => 1,
            //'UBI墨西哥专线'      => 1,
            //'UBI加拿大专线（带电）'  => 1,
            //'UBI俄罗斯专线（带电）'  => 1,
            //'UBI俄罗斯专线'      => 1,
            //'SRM简易挂号-俄罗斯' =>1,
            //'RM挂号-俄罗斯' =>1,
        ),
        'CARRIER_TEMPT_20' => array(
            'DHL快递小货-DH' => 1,
            'DHL快递小货-DH（带电）' => 1,
        ),

        // 速卖通的仓库显示配置
        'CARRIER_WHOUSE_NAME'=>array(
            '速卖通线上小包云途'=>'中邮东莞仓',
            '速卖通线上小包(鼎立通莆田仓)'=>'中邮莆田仓',
            '速卖通线上小包云途挂号'=>'中邮东莞仓',
            '速卖通线上小包挂号-无锡仓'=>'中邮无锡仓',
            '速卖通线上小包平邮-无锡仓'=>'中邮无锡仓',
            '速卖通线上小包挂号厦门仓'=>'中邮厦门仓',
            '速卖通线上小包平邮厦门仓'=>'中邮厦门仓',
            '速卖通线上挂号-东莞仓'=>'中邮东莞仓',
            '速卖通线上平邮-东莞仓'=>'中邮东莞仓',
            '速卖通线上小包挂号-南京仓'=>'中邮南京仓',
            '速卖通线上小包平邮-南京仓'=>'中邮南京仓',
        ),

        // 处于测试模式下的 运输方式
        'CARRIER_TEMPLATE_TEST' => [
            //'西班牙专线平邮'            => 'xbyzxpy',
            //'英国专线标准'              => 'ygzxbz',
            //'美国专线-安骏'             => 'mgzxaj',
            //'法国专线挂号'              => 'fgzxgh',
            //'意大利专线挂号'            => 'ydlzxgh',
            //'意大利专线平邮'            =>  'ydlzxpy',
            //        'DHl小包挂号'              =>  'DHLxbgh',  // TOD : 关于电话号码是否需要加上，尚未确定下来 // 2017-05-18 13:52 确认可添加电话号码
            //'德国专线挂号'              =>  'dgzxgh0',
            //'西班牙专线挂号'            =>   'xbyzxgh',
        ],

        //运输方式 是 pdf 的 ,pdf 路径
        'CARRIER_TEMPLATE_PDF_PATH'=>array(
            'wish邮特殊测试渠道-捷买送' => 'cache/pdf/xinyou/',
            'wish邮特殊测试渠道-顺友' => 'cache/pdf/xinyou/',
            'wish邮常规测试渠道-UBI' => 'cache/pdf/xinyou/',
            'wish邮常规测试渠道-CNE' => 'cache/pdf/xinyou/',
            'wish邮常规测试渠道-Wise' => 'cache/pdf/xinyou/',
            'JOOM-中欧挂号特货' => 'cache/pdf/joom/',
            'JOOM-中欧平邮特货' => 'cache/pdf/joom/',
            '德国专线-FT' => 'cache/pdf/feite/',
            '速卖通线上南京挂号-LX' => 'cache/pdf/smtpdf/',
            '速卖通线上南京平邮-LX' => 'cache/pdf/smtpdf/',
            'wish线上南京平邮-LX' => 'cache/pdf/xinyou/',
            'wish线上南京挂号-LX' => 'cache/pdf/xinyou/',
            '南京小包平邮-LX' => 'cache/pdf/lingxun/',
            '南京小包挂号-LX' => 'cache/pdf/lingxun/',
            'SpeedPAK-标准（带电）' => 'cache/pdf/ebay/',
            '速卖通线上挂号-南京仓' => 'cache/pdf/smtpdf/',
            '速卖通线上平邮-南京仓' => 'cache/pdf/smtpdf/',
            '南京小包挂号-GD' => 'cache/pdf/gude/',
            'wish线上南京挂号-GD' => 'cache/pdf/xinyou/',
            'wish线上南京平邮-GD' => 'cache/pdf/xinyou/',
            'wish线上EUB特货-LX' => 'cache/pdf/xinyou/',
            '西班牙专线平邮-YD' => 'cache/pdf/yida/',
            '义速宝俄罗斯经济-YD' => 'cache/pdf/yida/',
            '英国专线挂号-YHT' => 'cache/pdf/yihaitong/',
            'wish邮欧洲专线-WB' => 'cache/pdf/wanou/',
            '燕文专线追踪小包-特货' => 'cache/pdf/yanwen/',
            '燕文专线追踪小包-普货' => 'cache/pdf/yanwen/',
            '圆通-shopee特货（宅配）' => 'cache/pdf/SLS/',
            '圆通-shopee特货（店配）' => 'cache/pdf/SLS/',
            '圆通-shopee普货（店配）' => 'cache/pdf/SLS/',
            '英国虚拟仓平邮-FN' => 'cache/pdf/flybird/',
            '巴基斯坦内置包税小包-QHY' => 'cache/pdf/quanheyue/',
            '巴基斯坦特货包税小包-QHY' => 'cache/pdf/quanheyue/',
            '巴基斯坦普货包税小包-QHY' => 'cache/pdf/quanheyue/',
            '北京EUB-YW'  => 'cache/pdf/yanwen/',
            '英国专线挂号-FT' => 'cache/pdf/feite/',
            '印度专线带电-SZYJ' => 'cache/pdf/esb/',
            '印度专线普货-SZYJ' => 'cache/pdf/esb/',
            'DHL快递小货-DH' => 'cache/pdf/dhlkuaidi/',
            'DHL快递小货-DH（带电）' => 'cache/pdf/dhlkuaidi/',
            '英国虚拟仓专线挂号-SM' => 'cache/pdf/shangmeng/',
            '虚拟仓ubi加拿大特快专线' => 'cache/pdf/ubi/',
            '英国虚拟仓平邮-AJ' => 'cache/pdf/anjun/',
            'Wish邮深圳挂号' => 'cache/pdf/xinyou/',
            'MyMall线上小包' => 'cache/pdf/mymall/',
            '速卖通线上菜鸟专线经济' => 'cache/pdf/smtpdf/',
            '华中小包挂号-八国' => 'cache/pdf/ande/',
            '华中小包平邮' => 'cache/pdf/ande/',
            '华中小包挂号' => 'cache/pdf/ande/',
            '越南EUB-HYT' => 'cache/pdf/huayuntong/',
            '速卖通线上郑州平邮-AD' => 'cache/pdf/smtpdf/',
            '速卖通线上郑州挂号-AD' => 'cache/pdf/smtpdf/',
            'wish线上郑州平邮-AD' => 'cache/pdf/xinyou/',
            'wish线上郑州挂号-AD' => 'cache/pdf/xinyou/',
            'JOOM线上东莞挂号' => 'cache/pdf/joom/',
            'JOOM线上东莞平邮' => 'cache/pdf/joom/',
            '比利时平邮-HYD' => 'cache/pdf/huayuanda/',
            '中欧专线平邮-ebay' => 'cache/pdf/yuntu/',
            'wish线上广州eub带电-AJ' => 'cache/pdf/xinyou/',
            'wish线上武汉eub-AJ'   => 'cache/pdf/xinyou/',
            '美国虚拟仓普货大包-TJ' => 'cache/pdf/tengjia/',
            '美国虚拟仓内电大包-TJ' => 'cache/pdf/tengjia/',
            '美国虚拟仓特货大包-TJ' => 'cache/pdf/tengjia/',
            '美国虚拟仓特货-TJ' => 'cache/pdf/tengjia/',
            '美国虚拟仓内电-TJ' => 'cache/pdf/tengjia/',
            '美国虚拟仓普货-TJ' => 'cache/pdf/tengjia/',
            'wish邮广州挂号-WYT' => 'cache/pdf/xinyou/',
            'wish邮广州平邮-WYT' => 'cache/pdf/xinyou/',
            '速卖通线上挂号-HYT' => 'cache/pdf/smtpdf/',
            '速卖通线上平邮-HYT' => 'cache/pdf/smtpdf/',
            'wish邮成都挂号-HYT' => 'cache/pdf/xinyou/',
            'wish邮成都平邮-HYT' => 'cache/pdf/xinyou/',
            '印度专线-QHY' => 'cache/pdf/quanheyue/',
            '联邮通英国专线挂号特惠' => 'cache/pdf/4px/',
            '新加坡小包平邮' => 'cache/pdf/4px/',
            '新加坡小包挂号' => 'cache/pdf/4px/',
            'wish香港平邮-JHD' => 'cache/pdf/jinhuada/',
            'wish邮线上美国专线-SF' => 'cache/pdf/xinyou/',
            'Wish线上ubi加拿大特惠专线' => 'cache/pdf/xinyou/',
            '俄速通小包挂号' => 'cache/pdf/est/',
            '顺丰东欧小包挂号' => 'cache/pdf/shunfeng/',
            '美国专线-SF' => 'cache/pdf/shunfeng/',
            '欧洲专线平邮-FT' => 'cache/pdf/feite/',
            'JOOM-RU经济' => 'cache/pdf/joom/',
            'wish航空挂号小包特货-YW' => 'cache/pdf/xinyou/',
            'wish专线追踪小包特货-YW' => 'cache/pdf/xinyou/',
            'wish专线平邮小包特货-YW' => 'cache/pdf/xinyou/',
            'wish法国专线挂号特惠-YT' => 'cache/pdf/xinyou/',
            'wish线上UBI比利时平邮' => 'cache/pdf/xinyou/',
            'wish线上UBI墨西哥SCM专线挂号' => 'cache/pdf/xinyou/',
            'wish线上UBI澳邮专线挂号' => 'cache/pdf/xinyou/',
            'wish线上UBI加拿大专线挂号' => 'cache/pdf/xinyou/',
            'wish线上UBI西班牙专线平邮' => 'cache/pdf/xinyou/',
            'wish邮线上香港小包挂号-DSF' => 'cache/pdf/xinyou/',
            'wish邮线上香港小包平邮-DSF' => 'cache/pdf/xinyou/',
            'wish线上英国联邮通挂号特惠-DSF' => 'cache/pdf/xinyou/',
            'wish线上新邮挂号-DSF' => 'cache/pdf/xinyou/',
            'wish线上新邮微包平邮-DSF' => 'cache/pdf/xinyou/',
            '速卖通线上俄罗斯菜鸟特货专线-简易' => 'cache/pdf/smtpdf/',
            '速卖通线上菜鸟特货专线-超级经济'   => 'cache/pdf/smtpdf/',
            'wish线上新加坡挂号' => 'cache/pdf/xinyou/',
            'wish线上新加坡平邮' => 'cache/pdf/xinyou/',
            '澳大利亚专线-YD' => 'cache/pdf/yida/',
            'Wish邮广州挂号'       => 'cache/pdf/xinyou/',
            'Wish邮广州平邮'       => 'cache/pdf/xinyou/',
            '速卖通线上挂号-广州仓' => 'cache/pdf/smtpdf/',
            '速卖通线上平邮-广州仓' => 'cache/pdf/smtpdf/',
            '荷邮纯电挂号-YD' => 'cache/pdf/yida/',
            '荷邮纯电平邮-YD' => 'cache/pdf/yida/',
            '柬埔寨平邮-YD' => 'cache/pdf/yida/',
            '德国专线-YD' => 'cache/pdf/yida/',
            '顺邮宝挂号-SY' => 'cache/pdf/shunyou/',
            'Wsh线上EUB带电-HYD' => 'cache/pdf/xinyou/',
            'Wsh线上EUB-HYD'     => 'cache/pdf/xinyou/',
            'Wish线上香港挂号-YT' => 'cache/pdf/xinyou/',
            'Wish线上快速小包平邮-YT' => 'cache/pdf/xinyou/',
            'Wish线上香港平邮-YT' => 'cache/pdf/xinyou/',
            'Wish线上中美专线（特惠）-YT' => 'cache/pdf/xinyou/',
            'Wish线上中欧专线挂号-YT' => 'cache/pdf/xinyou/',
            'Wish线上中欧专线平邮-YT' => 'cache/pdf/xinyou/',
            'Wish线上西班牙特惠专线平邮-YT' => 'cache/pdf/xinyou/',
            'wish线上航空普货-YW'   => 'cache/pdf/xinyou/',
            'wish线上航空特货-YW'   => 'cache/pdf/xinyou/',
            'wish线上燕邮宝-YW'     => 'cache/pdf/xinyou/',
            'Wish线上顺邮宝平邮-SY' => 'cache/pdf/xinyou/',
            'Wish线上顺邮宝挂号-SY' => 'cache/pdf/xinyou/',
            '德国专线-DHL' => 'cache/pdf/DHL/',
            'LWE' => 'cache/pdf/lwe/',
            '速卖通线上小包4PX新邮经济小包'=>'cache/pdf/smtpdf/',
            '速卖通线上小包无忧标准'=>'cache/pdf/smtpdf/',
            '速卖通线上小包无忧标准（非普货）'=>'cache/pdf/smtpdf/',
            '速卖通线上小包无忧简易'=>'cache/pdf/smtpdf/',
            '速卖通线上小包无忧简易-西班牙'=>'cache/pdf/smtpdf/',
            '速卖通线上小包中外运-西邮经济'=>'cache/pdf/smtpdf/',
            '速卖通线上小包顺友航空经济小包深圳仓'=>'cache/pdf/smtpdf/',
            '速卖通线上小包云途挂号'=>'cache/pdf/smtpdf/',
            '速卖通线上小包挂号厦门仓'=>'cache/pdf/smtpdf/',
            '速卖通线上小包挂号-无锡仓'=>'cache/pdf/smtpdf/',
            '速卖通线上燕文航空经济小包'=>'cache/pdf/smtpdf/',
            '速卖通线上顺丰航空经济小包'=>'cache/pdf/smtpdf/',
            '速卖通线上小包无忧标准-普货' => 'cache/pdf/smtpdf/',
            '速卖通线上小包无忧简易-ES' => 'cache/pdf/smtpdf/',
            // hank 2018/02/26
            '速卖通线上顺丰国际经济小包'=>'cache/pdf/smtpdf/',
            '速卖通线上无忧优先'=>'cache/pdf/smtpdf/',
            '速卖通线上小包挂号-南京仓'=>'cache/pdf/smtpdf/',
            '速卖通线上小包挂号(鼎立莆田仓)'=>'cache/pdf/smtpdf/',
            '速卖通线上小包平邮厦门仓'=>'cache/pdf/smtpdf/',
            '速卖通线上小包平邮-无锡仓'=>'cache/pdf/smtpdf/',
            '速卖通线上小包平邮-南京仓'=>'cache/pdf/smtpdf/',
            '速卖通线上小包云途'=>'cache/pdf/smtpdf/',
            '速卖通线上小包(鼎立通莆田仓)'=>'cache/pdf/smtpdf/',
            '速卖通线上菜鸟经济-RU' => 'cache/pdf/smtpdf/',
            '速卖通线上平邮带电-深圳仓' => 'cache/pdf/smtpdf/',
            '速卖通线上无忧集运平邮-SA' => 'cache/pdf/smtpdf/',
            '速卖通线上无忧集运挂号-SA' => 'cache/pdf/smtpdf/',
            '速卖通线上无忧集运平邮-AE' => 'cache/pdf/smtpdf/',
            '速卖通线上无忧集运挂号-AE' => 'cache/pdf/smtpdf/',

            '顺邮宝平邮'=>'cache/pdf/shunyou/',
            '顺邮宝挂号'=>'cache/pdf/shunyou/',
            '顺友通平邮'=>'cache/pdf/shunyou/',
            '顺友通挂号'=>'cache/pdf/shunyou/',
            '顺达宝平邮'=>'cache/pdf/shunyou/',
            '顺邮宝平邮2-SY' => 'cache/pdf/shunyou/',

            '线下EUB(加拿大)鼎立'=>'cache/pdf/dingli/',
            '亚欧快运陆运挂号'=>'cache/pdf/tea/',
            '欧速通'=>'cache/pdf/ost/',
            '欧速通英国专线挂号'=>'cache/pdf/ost/',
            '欧速通（带电）'=>'cache/pdf/ost/',
            '欧速通英国专线挂号(带电)'=>'cache/pdf/ost/',
            '卢森堡挂号' => 'cache/pdf/ost/',
            'Linio物流'=>'cache/pdf/mailAmericas/',
            '顺丰国际小包'=>'cache/pdf/shunfeng/',
            '出口易小包挂号'=>'cache/pdf/ChuKou1/',
            '出口易小包平邮'=>'cache/pdf/ChuKou1/',

            'UBI加拿大专线'=>'cache/pdf/ubi/',
            'UBI澳大利亚专线'=>'cache/pdf/ubi/',
            'UBI澳大利亚专线（带电）'=>'cache/pdf/ubi/',
            'UBI墨西哥专线（带电）'=>'cache/pdf/ubi/',
            'UBI加拿大专线（带电）'=>'cache/pdf/ubi/',
            'UBI俄罗斯专线（带电）'=>'cache/pdf/ubi/',
            'UBI俄罗斯专线'=>'cache/pdf/ubi/',
            'UBI澳大利亚平邮'=>'cache/pdf/ubi/',
            'UBI澳大利亚平邮（带电）'=>'cache/pdf/ubi/',
            'UBI墨西哥专线'=>'cache/pdf/ubi/',
            'UBI欧盟28国-半程查件'=>'cache/pdf/ubi/',

            '线上中邮易递宝（万邑通）'=>'cache/pdf/wyt/',
            '马来西亚平邮易递宝（万邑通）'=>'cache/pdf/wyt/',
            '香港平邮易递宝（万邑通）'=>'cache/pdf/wyt/',
            '线上中邮万邑通-深圳邮局'=>'cache/pdf/wyt/',


            'SLS-shopee专用'=>'cache/pdf/SLS/',
            'SLS-shopee专用(越南)' =>'cache/pdf/SLS/',
            // hank 2017/11/23 14:09
            'SLS平邮-shopee专用'=>'cache/pdf/SLS/',
            'SLS平邮-shopee专用（越南）' => 'cache/pdf/SLS/',
            'SLS-shopee （印度尼西亚）' => 'cache/pdf/SLS/',
            'SLS-shopee（马来西亚）' => 'cache/pdf/SLS/',
            'SLS-shopee（泰国）' => 'cache/pdf/SLS/',
            'SLS-shopee（新加坡）' => 'cache/pdf/SLS/',
            'SLS-shopee  Standar EKspres印尼' => 'cache/pdf/SLS/',
            '圆通-shopee' => 'cache/pdf/SLS/',
            'DHL-shopee（泰国）' => 'cache/pdf/SLS/',
            '荷兰邮政小包平邮'=>'cache/pdf/wenhui/',
            '荷兰邮政小包挂号'=>'cache/pdf/wenhui/',
            '俄罗斯小包WH'=>'cache/pdf/wenhui/',
            '新疆小包挂号-WH'=>'cache/pdf/wenhui/',
            // hank 2018/3/15 9:45
            '比邮挂号-WH'=>'cache/pdf/wenhui/',
            '比邮平邮-WH'=>'cache/pdf/wenhui/',
            '比邮挂号26国-WH'=>'cache/pdf/wenhui/',

            '德国专线平邮'=>'cache/pdf/yuntu/',

            'Wish平邮-广州仓'=>'cache/pdf/xinyou/',
            '广州小包挂号-星邮'=>'cache/pdf/xinyou/',
            '广州小包平邮-星邮'=>'cache/pdf/xinyou/',
            'Wish邮东莞挂号' => 'cache/pdf/xinyou/',
            '广州小包挂号'=>'cache/pdf/kuajing/',
            '广州小包平邮'=>'cache/pdf/kuajing/',

            'DHL小包挂号-德国预清关'=>'cache/pdf/DHL/',
            'DHL小包平邮-德国预清关'=>'cache/pdf/DHL/',
            'DHl小包挂号'=>'cache/pdf/DHL/',
            'DHl小包挂号(带电)'=>'cache/pdf/DHL/',
            // hank 2017/11/24 16:42
            '美国专线-DHL'=>'cache/pdf/DHL/',
            // hank 2018/3/30 13:45
            'DHL小包平邮(带电)'=>'cache/pdf/DHL/',
            'DHL小包平邮'=>'cache/pdf/DHL/',


            '英国直飞专线-安骏'=>'cache/pdf/anjun/',
            '美国专线-安骏'=>'cache/pdf/anjun/',
            '德国专线-安骏'=>'cache/pdf/anjun/',
            '法国专线-安骏'=>'cache/pdf/anjun/',

            '比利时小包非欧盟' => 'cache/pdf/ems/',
            //'比利时小包'=>'cache/pdf/ems/',
            '中美专线'=>'cache/pdf/ems/',
            '中美专线-带电'=>'cache/pdf/ems/',

            'IB中美专线（标准）' => 'cache/pdf/ib/',
            'IB中美专线（快速-带电）' => 'cache/pdf/ib/',

            //'E速宝'=>'cache/pdf/ems/',
            // hank 2018/2/28 14:52
            'CTAM小包平邮-液体'=>'cache/pdf/feite/',
            'CTAM小包平邮'=>'cache/pdf/feite/',
            '法国专线-万欧'=>'cache/pdf/wanou/',
            '德国专线-万欧'=>'cache/pdf/wanou/',
            '意大利专线-万欧'=>'cache/pdf/wanou/',
            '西班牙专线-万欧'=>'cache/pdf/wanou/',
            '法国专线标准-WB' => 'cache/pdf/wanou/',
            //'华中小包挂号'=>'cache/pdf/ande/',
            //'华中小包挂号-八国'=>'cache/pdf/ande/',
            //'华中小包平邮'=>'cache/pdf/ande/',

            '荷兰小包平邮-YW' => 'cache/pdf/yanwen/',
            '荷兰小包挂号-YW' => 'cache/pdf/yanwen/',
            '土耳其邮政挂号-YW'  => 'cache/pdf/yanwen/',
            '土耳其邮政平邮-YW'  => 'cache/pdf/yanwen/',
            '新加坡小包挂号-YW'  => 'cache/pdf/yanwen/',
            '马来西亚小包挂号-YW'  => 'cache/pdf/yanwen/',
            '新加坡小包平邮-YW'  => 'cache/pdf/yanwen/',
            '马来西亚小包平邮-YW'  => 'cache/pdf/yanwen/',
            '香港小包挂号-YW'  => 'cache/pdf/yanwen/',
            '香港小包挂号四国-YW'  => 'cache/pdf/yanwen/',
            '香港小包平邮-YW'  => 'cache/pdf/yanwen/',
            '西邮经济小包-YW'  => 'cache/pdf/yanwen/',
            '重庆小包挂号-YW'  => 'cache/pdf/yanwen/',
            '重庆小包平邮-YW'  => 'cache/pdf/yanwen/',
            '燕邮宝平邮内电-YW'  => 'cache/pdf/yanwen/',
            '比利时小包平邮-YW'  => 'cache/pdf/yanwen/',
            '比利时小包挂号-YW'  => 'cache/pdf/yanwen/',
            // hank 2018/2/28 14:52
            'Wish邮挂号-YW'=>'cache/pdf/yanwen/',
            // hank 2017/12/6 14:09 优兰达 改成 eub自画模板
            //'线下EUB广州-YLD'  => 'cache/pdf/youlanda/',
            //'线下EUB广州(带电)-YLD'  => 'cache/pdf/youlanda/',

            //'SRM简易挂号-俄罗斯' =>'cache/pdf/guanda/',
            //'RM挂号-俄罗斯' =>'cache/pdf/guanda/',
            // ran 2017-10-26 老挝新接口返回PDF
            '老挝小包平邮-TY' =>'cache/pdf/tongyou/',
            '老挝小包挂号-TY' =>'cache/pdf/tongyou/',
            '老挝小包平邮快线-TY' =>'cache/pdf/tongyou/',
            'jumia Soko物流'=>'cache/pdf/jumia/',
            // hank 2017/11/12
            'jumia Soko物流-埃及'=>'cache/pdf/jumia/',
            'jumia Soko物流-象牙海岸'=>'cache/pdf/jumia/',

            //2017-11-8 abel
            '顺丰荷兰小包挂号' =>'cache/pdf/shunfeng/',
            '顺丰荷兰小包平邮'=>'cache/pdf/shunfeng/',
            '顺丰澳大利亚小包挂号'=>'cache/pdf/shunfeng/',
            // hank 2017/11/9 15:40
            '北京小包平邮-YW'=>'cache/pdf/yanwen/',
            '北京小包挂号-YW'=>'cache/pdf/yanwen/',
            'Wish邮平邮-YW'=>'cache/pdf/yanwen/',
            // hank 2017/12/13 14:14
            'Wish邮平邮-DL'=>'cache/pdf/xinyou/',
            '中欧特快专线平邮'=>'cache/pdf/yuntu/',
            //'华南小包平邮（快速）'=>'cache/pdf/yuntu/',
            '中欧专线平邮'=>'cache/pdf/yuntu/',
            // hank 2018/3/17 9:28
            '英国虚拟仓平邮'=>'cache/pdf/yuntu/',
            '俄罗斯平邮-YT' => 'cache/pdf/yuntu/',
            '快速小包平邮-YT' => 'cache/pdf/yuntu/',
            '西班牙特惠专线平邮-YT' => 'cache/pdf/yuntu/',

            '欧洲专线平邮-WO'=>'cache/pdf/wanou/',
            // hank 2018/1/30 16:10
            '燕邮宝平邮-YW'=>'cache/pdf/yanwen/',
            '航空经济小包普货-YW'=>'cache/pdf/yanwen/',
            '航空经济小包特货-YW'=>'cache/pdf/yanwen/',
            '航空挂号小包普货-YW'=>'cache/pdf/yanwen/',
            '航空挂号小包特货-YW'=>'cache/pdf/yanwen/',
            '英国专线微包-YW'=>'cache/pdf/yanwen/',
            'DHL经济平邮'=>'cache/pdf/DHL/',
            'CTAM小包平邮-普货'=>'cache/pdf/feite/',
            'CTAM小包挂号'=>'cache/pdf/feite/',
            '英国专线平邮-FT' => 'cache/pdf/feite/',
            '意大利专线平邮-FT' => 'cache/pdf/feite/',

            //abel 2018 02 01
            '台湾小包挂号-GY'=>'cache/pdf/guoyang/',
            '台湾小包平邮-GY'=>'cache/pdf/guoyang/',
            '台湾小包平邮-GY(ebay)' => 'cache/pdf/guoyang/',
            '台湾小包挂号-GY(ebay)' => 'cache/pdf/guoyang/',
            // hank 2018/3/15 9:46
            'Wish邮南京挂号-YW'=>'cache/pdf/yanwen/',
            'Wish邮南京平邮-YW'=>'cache/pdf/yanwen/',
            // hank 2018/3/30 16:50
            'Wish邮厦门挂号-GD'=>'cache/pdf/xinyou/',
            'Wish邮厦门平邮-GD'=>'cache/pdf/xinyou/',
            'Wish邮厦门挂号带电-GD'=>'cache/pdf/xinyou/',
            'Wish邮厦门平邮带电-GD'=>'cache/pdf/xinyou/',
            'Wish邮深圳平邮' => 'cache/pdf/xinyou/',
            'Wish邮深圳平邮（带电）' => 'cache/pdf/xinyou/',
            'wish线上Fly挂号-FT'     => 'cache/pdf/xinyou/',
            'wish线上Fly平邮-FT'     => 'cache/pdf/xinyou/',
            'Wish线上老挝平邮'       => 'cache/pdf/xinyou/',
            'Wish线上老挝平邮-特货'  => 'cache/pdf/xinyou/',
            // hank 2018/4/2 14:16
            '新疆EUB-WH'=>'cache/pdf/wenhui/',
            '新疆中邮挂号-WH' => 'cache/pdf/wenhui/',
            // mina 20180409
            '香港挂号-JHD'  => 'cache/pdf/jinhuada/',
            '香港平邮-JHD' => 'cache/pdf/jinhuada/',
            '香港wish平邮-JHD' => 'cache/pdf/jinhuada/',
            'GLS物流' => 'cache/pdf/gls', // mina 20180420
            'SpeedPAK-经济' => 'cache/pdf/ebay/',
            'SpeedPAK-标准' => 'cache/pdf/ebay/', // leo 20180808

            'ECMS-wadi' => 'cache/pdf/wadi/',
            'EPC-Wish' => 'cache/pdf/epc/',
            'EPC-Wish特货' => 'cache/pdf/xinyou/',

            'JOOM-RU简易' => 'cache/pdf/joom/',
            'JOOM-RU挂号' => 'cache/pdf/joom/',
            'JOOM-RU挂号特货' => 'cache/pdf/joom/',
            'JOOM-中欧挂号' => 'cache/pdf/joom/',
            'JOOM-中欧平邮' => 'cache/pdf/joom/',

        ),


        //八个垃圾国家 一个运输方式还要求用8种面单 真是欺人太甚!!!! 搞得配置文件乌烟瘴气
        //这个地方配置之后 就可以直接在 CARRIER_TEMPT 配置中 找到正确的模板了
        'CARRIER_MORE_TEMPLATE'=>array(
            '荷邮纯电挂号-YD' => array(
                'IT' => '荷邮纯电挂号-YD_IT',
                'CZ' => '荷邮纯电挂号-YD_CZ',
                'PL' => '荷邮纯电挂号-YD_PL',
                'LU' => '荷邮纯电挂号-YD_LU'
            ),

            '福州小包挂号'=>array(
                'FR'=>'福州小包挂号_FR',
                'NZ'=>'福州小包挂号_NZ',
                'DE'=>'福州小包挂号_DE',
                'HR'=>'福州小包挂号_group1',
                'PL'=>'福州小包挂号_group1',
                'SI'=>'福州小包挂号_group1',
                'RT'=>'福州小包挂号_group1',
                'CZ'=>'福州小包挂号_group1',
                'AU'=>'福州小包挂号_AU',
            ),
            '东莞小包挂号-八国'=>array(
                'DE'=>'东莞小包挂号-八国_DE',
                'FR'=>'东莞小包挂号-八国_FR',
                'NZ'=>'东莞小包挂号-八国_NZ',
                'AU'=>'东莞小包挂号-八国_AU',
                'SK'=>'东莞小包挂号-八国_5G',
                'PL'=>'东莞小包挂号-八国_5G',
                'HR'=>'东莞小包挂号-八国_5G',
                'CZ'=>'东莞小包挂号-八国_5G',
                'SI'=>'东莞小包挂号-八国_5G',
            ),
            '厦门小包挂号(带电)'=>array(
                'DE'=>'厦门小包挂号(带电)-八国_DE',
                'FR'=>'厦门小包挂号(带电)-八国_FR',
                'NZ'=>'厦门小包挂号(带电)-八国_NZ',
                'NO'=>'厦门小包挂号(带电)-八国_NO',
                'SK'=>'厦门小包挂号(带电)-八国_5G',
                'PL'=>'厦门小包挂号(带电)-八国_5G',
                'HR'=>'厦门小包挂号(带电)-八国_5G',
                'CZ'=>'厦门小包挂号(带电)-八国_5G',
                'SI'=>'厦门小包挂号(带电)-八国_5G',
                'AU'=>'厦门小包挂号(普货)-八国_AU',
            ),

            '厦门小包挂号(普货)'=>array(
                'DE'=>'厦门小包挂号(普货)-八国_DE',
                'FR'=>'厦门小包挂号(普货)-八国_FR',
                'NZ'=>'厦门小包挂号(普货)-八国_NZ',
                'SK'=>'厦门小包挂号(普货)-八国_5G',
                'PL'=>'厦门小包挂号(普货)-八国_5G',
                'HR'=>'厦门小包挂号(普货)-八国_5G',
                'CZ'=>'厦门小包挂号(普货)-八国_5G',
                'SI'=>'厦门小包挂号(普货)-八国_5G',
                'NO'=>'厦门小包挂号(带电)-八国_NO',
                'AU'=>'厦门小包挂号(带电)-八国_AU',
            ),

            '速卖通线上小包云途挂号'=>array(
                'DE'=>'速卖通线上小包云途挂号_8G',
                'FR'=>'速卖通线上小包云途挂号_8G',
                'NZ'=>'速卖通线上小包云途挂号_8G',
                'SK'=>'速卖通线上小包云途挂号_8G',
                'PL'=>'速卖通线上小包云途挂号_8G',
                'HR'=>'速卖通线上小包云途挂号_8G',
                'CZ'=>'速卖通线上小包云途挂号_8G',
                'SI'=>'速卖通线上小包云途挂号_8G',
            ),

            '速卖通线上小包挂号-无锡仓'=>array(
                'DE'=>'速卖通线上小包挂号-无锡仓_8G',
                'FR'=>'速卖通线上小包挂号-无锡仓_8G',
                'NZ'=>'速卖通线上小包挂号-无锡仓_8G',
                'SK'=>'速卖通线上小包挂号-无锡仓_8G',
                'PL'=>'速卖通线上小包挂号-无锡仓_8G',
                'HR'=>'速卖通线上小包挂号-无锡仓_8G',
                'CZ'=>'速卖通线上小包挂号-无锡仓_8G',
                'SI'=>'速卖通线上小包挂号-无锡仓_8G',
            ),
            '速卖通线上小包挂号厦门仓'=>array(
                'DE'=>'速卖通线上小包挂号厦门仓_8G',
                'FR'=>'速卖通线上小包挂号厦门仓_8G',
                'NZ'=>'速卖通线上小包挂号厦门仓_8G',
                'SK'=>'速卖通线上小包挂号厦门仓_8G',
                'PL'=>'速卖通线上小包挂号厦门仓_8G',
                'HR'=>'速卖通线上小包挂号厦门仓_8G',
                'CZ'=>'速卖通线上小包挂号厦门仓_8G',
                'SI'=>'速卖通线上小包挂号厦门仓_8G',
            ),
            // hank 2018/2/3 10:26
            'E速宝挂号'=>array(
                'RU'=>'E速宝挂号-RU',
                'BR'=>'E速宝挂号-BR',
            ),

            '深圳小包SH平邮' => array(
                'US' => '深圳小包SH平邮_US',
                'GB' => '深圳小包SH平邮_GB',
                'RU' => '深圳小包SH平邮_RU'
            ),
            '速卖通线上挂号-广州仓' => [
                  'DE' => '速卖通线上挂号-广州仓_DE',
                  'CZ' => '速卖通线上挂号-广州仓_DE',
                  'SK' => '速卖通线上挂号-广州仓_DE',
                  'PL' => '速卖通线上挂号-广州仓_DE',
                  'FR' => '速卖通线上挂号-广州仓_DE',
                  'NZ' => '速卖通线上挂号-广州仓_DE',
                  'HR' => '速卖通线上挂号-广州仓_DE',
                  'SI' => '速卖通线上挂号-广州仓_DE',
            ],
            'wish邮成都挂号-HYT' => [
              'DE' => 'wish邮成都挂号-HYT_DE',
              'FR' => 'wish邮成都挂号-HYT_DE',
              'CZ' => 'wish邮成都挂号-HYT_DE',
              'SK' => 'wish邮成都挂号-HYT_DE',
              'PL' => 'wish邮成都挂号-HYT_DE',
              'NZ' => 'wish邮成都挂号-HYT_DE',
              'HR' => 'wish邮成都挂号-HYT_DE',
              'SI' => 'wish邮成都挂号-HYT_DE'
            ],
            '速卖通线上挂号-HYT' => [
              'CZ' => '速卖通线上挂号-HYT_CZ',
              'SK' => '速卖通线上挂号-HYT_CZ',
              'FR' => '速卖通线上挂号-HYT_CZ',
              'DE' => '速卖通线上挂号-HYT_CZ',
              'PL' => '速卖通线上挂号-HYT_CZ',
              'NZ' => '速卖通线上挂号-HYT_CZ',
              'HR' => '速卖通线上挂号-HYT_CZ',
              'SI' => '速卖通线上挂号-HYT_CZ',
            ],
            'wish邮广州挂号-WYT' => [
                'CZ' => 'wish邮广州挂号-WYT_DE',
                'SK' => 'wish邮广州挂号-WYT_DE',
                'FR' => 'wish邮广州挂号-WYT_DE',
                'DE' => 'wish邮广州挂号-WYT_DE',
                'PL' => 'wish邮广州挂号-WYT_DE',
                'NZ' => 'wish邮广州挂号-WYT_DE',
                'HR' => 'wish邮广州挂号-WYT_DE',
                'SI' => 'wish邮广州挂号-WYT_DE',
            ],
            '速卖通线上郑州挂号-AD' => [
                'CZ' => '速卖通线上郑州挂号-AD-8',
                'SK' => '速卖通线上郑州挂号-AD-8',
                'FR' => '速卖通线上郑州挂号-AD-8',
                'DE' => '速卖通线上郑州挂号-AD-8',
                'PL' => '速卖通线上郑州挂号-AD-8',
                'NZ' => '速卖通线上郑州挂号-AD-8',
                'HR' => '速卖通线上郑州挂号-AD-8',
                'SI' => '速卖通线上郑州挂号-AD-8',
            ],
            'wish线上郑州挂号-AD' => [
                'CZ' => 'wish线上郑州挂号-AD-8',
                'SK' => 'wish线上郑州挂号-AD-8',
                'FR' => 'wish线上郑州挂号-AD-8',
                'DE' => 'wish线上郑州挂号-AD-8',
                'PL' => 'wish线上郑州挂号-AD-8',
                'NZ' => 'wish线上郑州挂号-AD-8',
                'HR' => 'wish线上郑州挂号-AD-8',
                'SI' => 'wish线上郑州挂号-AD-8',
            ],
            'Wish邮深圳挂号' => [
                  'CZ' => 'Wish邮深圳挂号-8',
                  'SK' => 'Wish邮深圳挂号-8',
                  'FR' => 'Wish邮深圳挂号-8',
                  'DE' => 'Wish邮深圳挂号-8',
                  'PL' => 'Wish邮深圳挂号-8',
                  'NZ' => 'Wish邮深圳挂号-8',
                  'HR' => 'Wish邮深圳挂号-8',
                  'SI' => 'Wish邮深圳挂号-8',
            ],
            'wish线上南京挂号-GD' => [
                'CZ' => 'wish线上南京挂号-GD_DE',
                'SK' => 'wish线上南京挂号-GD_DE',
                'FR' => 'wish线上南京挂号-GD_DE',
                'DE' => 'wish线上南京挂号-GD_DE',
                'PL' => 'wish线上南京挂号-GD_DE',
                'NZ' => 'wish线上南京挂号-GD_DE',
                'HR' => 'wish线上南京挂号-GD_DE',
                'SI' => 'wish线上南京挂号-GD_DE',
            ],
            '速卖通线上挂号-南京仓' => [
                'CZ' => '速卖通线上挂号-南京仓-GD-8',
                'SK' => '速卖通线上挂号-南京仓-GD-8',
                'FR' => '速卖通线上挂号-南京仓-GD-8',
                'DE' => '速卖通线上挂号-南京仓-GD-8',
                'PL' => '速卖通线上挂号-南京仓-GD-8',
                'NZ' => '速卖通线上挂号-南京仓-GD-8',
                'HR' => '速卖通线上挂号-南京仓-GD-8',
                'SI' => '速卖通线上挂号-南京仓-GD-8',
            ],
            'wish线上南京挂号-LX' => [
                'CZ' => 'wish线上南京挂号-LX-8',
                'SK' => 'wish线上南京挂号-LX-8',
                'FR' => 'wish线上南京挂号-LX-8',
                'DE' => 'wish线上南京挂号-LX-8',
                'PL' => 'wish线上南京挂号-LX-8',
                'NZ' => 'wish线上南京挂号-LX-8',
                'HR' => 'wish线上南京挂号-LX-8',
                'SI' => 'wish线上南京挂号-LX-8',
            ],
            '速卖通线上南京挂号-LX' => [
                'CZ' => '速卖通线上南京挂号-LX-8',
                'SK' => '速卖通线上南京挂号-LX-8',
                'FR' => '速卖通线上南京挂号-LX-8',
                'DE' => '速卖通线上南京挂号-LX-8',
                'PL' => '速卖通线上南京挂号-LX-8',
                'NZ' => '速卖通线上南京挂号-LX-8',
                'HR' => '速卖通线上南京挂号-LX-8',
                'SI' => '速卖通线上南京挂号-LX-8',
            ],
            'wish邮特殊测试渠道-顺友' => [
                'CZ' => 'wish邮特殊测试渠道-8',
                'SK' => 'wish邮特殊测试渠道-8',
                'FR' => 'wish邮特殊测试渠道-8',
                'DE' => 'wish邮特殊测试渠道-8',
                'PL' => 'wish邮特殊测试渠道-8',
                'NZ' => 'wish邮特殊测试渠道-8',
                'HR' => 'wish邮特殊测试渠道-8',
                'SI' => 'wish邮特殊测试渠道-8',
                'ES' => 'wish邮特殊测试渠道-8'
            ],
            'wish邮特殊测试渠道-捷买送' => [
                'CZ' => 'wish邮特殊测试渠道-8',
                'SK' => 'wish邮特殊测试渠道-8',
                'FR' => 'wish邮特殊测试渠道-8',
                'DE' => 'wish邮特殊测试渠道-8',
                'PL' => 'wish邮特殊测试渠道-8',
                'NZ' => 'wish邮特殊测试渠道-8',
                'HR' => 'wish邮特殊测试渠道-8',
                'SI' => 'wish邮特殊测试渠道-8',
                'ES' => 'wish邮特殊测试渠道-8'
            ]

        ),

        'LOAD_EXT_CONFIG'=>'regetpdf,allcarriers,allaction,message,rediskey,orders,wlapi',

    );