<?php
/**
 * @Copyright (C), 2018-2019, 卓士网络科技有限公司, shawn.sean@foxmail.com
 * @Name LoginController.class.php
 * @Author Shawn
 * @Version v1.0
 * @Date: 2018/8/20
 * @Time: 18:15
 * @Description 手机端登陆
 */
namespace Mobile\Controller;
use Order\Model\EbayStoreModel;
use Package\Model\ErpEbayUserModel;

class LoginController extends BaseController
{
    public function _initialize()
    {
//        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 登录页面
     * @author Shawn
     * @date 2018/8/21
     */
    public function login()
    {
        //如果已经登录了直接跳转到首页
        if(session("truename")){
            $this->success('已登录，自动跳转',U('Mobile/Index/delivery'));
        }else{
            $this->display();
        }
    }

    /**
     * 登录验证
     * @author Shawn
     * @date 2018/8/21
     */
    public function loginAuth()
    {
        $userModel = new ErpEbayUserModel();
        $accountNo = I('accountNo');
        $pwd = I("pwd");
        if(empty($accountNo)){
            $this->ajaxReturn(['status'=>'-1','msg'=>'用户名为空，请重新输入']);
        }
        if(empty($pwd)){
            $this->ajaxReturn(['status'=>'-2','msg'=>'密码为空，请重新输入']);
        }
        // 使用工号登录
        if (preg_match('/^\d+$/', $accountNo))
        {
            $userName = $userModel->where(['id'=>$accountNo])->getField('username');
            if(!empty($userName)){
                $accountNo = $userName;
            }
        }
        //找下是否存在这个账号
        $userData = $userModel->where(['username'=>$accountNo])
            ->field("id,user,power,ebayaccounts,message,record,truename,viewstore,vieworder,password,username")
            ->find();
        if(empty($userData)){
            $this->ajaxReturn(['status'=>'-1','msg'=>'用户名错误，请重新输入']);
        }else{
            //加密
            $pass        = md5(md5($pwd));
            if($userData['password'] != $pass){
                $this->ajaxReturn(['status'=>'-2','msg'=>'密码错误，请重新输入']);
            }else{
                //外网访问人员
                $Allow_Users = include(dirname(dirname(THINK_PATH)) . '/include/allow_users.php');
                $host = $_SERVER['HTTP_HOST'];
                if($host == 'terryzhang.vicp.io'|| $host == 'sukidong.iask.in'){
                    if(!in_array($userData['username'],$Allow_Users)){
                        $this->ajaxReturn(['status'=>'-3','msg'=>'登录未授权，请联系IT！']);
                    }
                }
                $_SESSION['id']             = $userData['id'];
                $_SESSION['user']			= $userData['user'];
                $_SESSION['power'] 			= $userData['power'];
                $_SESSION['truename']		= $userData['username'];
                $_SESSION['ebayaccounts']	= $userData['ebayaccounts'];
                $_SESSION['messages']		= $userData['message'];
                $_SESSION['pagesize']		= $userData['record'] ? $userData['record'] : 25;
                $_SESSION['tname']          = $userData['truename'];
                $_SESSION['vieworderstatus']= $userData['vieworder'];//可见订单的权限
                $viewStore                  = trim($userData['viewstore'],',');
                //可见仓库的权限
                $storeArr = $this->getStoreArrIndexId();
                $viewStoreArr = explode(',',$viewStore);
                if(count($viewStoreArr) == 0){
                    $_SESSION['viewstore']=" and a.ebay_warehouse='' ";
                }

                if(count($viewStoreArr) >= 1){
                    $temp = str_replace(',','\' or a.ebay_warehouse=\'',$viewStore);
                    $_SESSION['viewstore'] = ' and ( a.ebay_warehouse=\''.$temp.'\')';
                }

                if(count($storeArr) == count($viewStoreArr)){
                    $_SESSION['viewstore'] = '';
                }
                $updateData['logtime'] = date('Y-m-d H:i:s');
                $updateData['ip'] = $this->getRealIpAddr();
                $userModel->where(['username'=>$userData['username']])->save($updateData);
                $this->ajaxReturn(['status'=>'1','msg'=>'登录成功']);
            }
        }
    }

    /**
     * 获取仓库信息
     * @return array
     * @author Shawn
     * @date 2018/8/21
     */
    public function getStoreArrIndexId()
    {
        $arr = array();
        $ebayStoreModel = new EbayStoreModel();
        $storeData = $ebayStoreModel->field("store_name,id")
            ->select();
        foreach($storeData as $v){
            $arr[$v['id']] = $v['store_name'];
        }
        return $arr;
    }

    /**
     * 退出登录
     * @author Shawn
     * @date 2018/8/21
     */
    public function loginOut()
    {
        session_destroy();
        $this->success("退出成功",U('Mobile/Login/login'));
    }
}